---
subtitle: Assessing the validity of a calcifying oral biofilm model as a suitable proxy for dental calculus
date-modified: last-modified
citation:
  type: report
  container-title: "bioRxiv"
  doi: "10.1101/2023.05.23.541904"
  url: https://doi.org/10.1101/2023.05.23.541904
author: 
  - name: Bjørn Peare Bartholdy
    orcid: 0000-0003-3985-1016
    corresponding: true
    affiliations:
      - ref: leiden
  - name: Irina M. Velsko
    orcid: 0000-0001-9810-9917
    affiliations:
      - ref: mpi
  - name: Shira Gur-Arieh
    orcid: 0000-0003-2015-7817
    affiliations:
      - ref: haifa
      - ref: mun
  - name: Zandra Fagernäs
    orcid: 0000-0003-2667-3556
    affiliations:
      - ref: mpi
      - ref: globe
  - name: Christina Warinner
    orcid: 0000-0002-4528-5877
    affiliations:
      - ref: harv
      - ref: mpi
  - name: Amanda G. Henry
    orcid: 0000-0002-2923-4199
    affiliations:
      - ref: leiden
affiliations:
  - id: leiden
    name: Leiden University
    department: Faculty of Archaeology
    city: Leiden
    country: The Netherlands
  - id: mpi
    name: Max Planck Institute for Evolutionary Anthropology
    department: Department of Archaeogenetics
    city: Leipzig
    country: Germany
  - id: globe
    name: University of Copenhagen
    department: Globe Institute
    city: Copenhagen
    country: Denmark
  - id: haifa
    name: University of Haifa
    department: The Leon Recanati Institute for Maritime Studies
    city: Haifa
    country: Israel
  - id: mun
    name: Ludwig Maximilian University
    department: Institute for Pre- and Protohistoric Archaeology and Archaeology of the Roman Provinces
    city: Munich
    country: Germany
  - id: harv
    name: Department of Anthropology, Harvard University
    department: Department of Anthropology
    city: Cambridge, MA
    country: USA
---

# Article 1 {#byoc-valid}

::: {.content-visible when-format="pdf"}

\footnotesize

**Co-authors and contributions:**

- Irina M. Velsko, Max Planck Institute for Evolutionary Anthropology
- Shira Gur-Arieh, University of Haifa, Ludwig Maximilian University
- Zandra Fagernäs, Max Planck Institute for Evolutionary Anthropology, University of Copenhagen
- Christina Warinner, Max Planck Institute for Evolutionary Anthropology, Harvard University
- Amanda G. Henry, Leiden University

<!-- generated with tenzing (https://rollercoaster.shinyapps.io/tenzing/) -->
Conceptualization: B.P.B., I.M.V., S.G.-A., and A.G.H. Data curation: B.P.B. Formal analysis: B.P.B., I.M.V., and S.G.-A. Funding acquisition: C.W. and A.G.H. Investigation: B.P.B., S.G.-A., and Z.F. Methodology: B.P.B., I.M.V., and S.G.-A. Resources: C.W. and A.G.H. Software: B.P.B. Supervision: C.W. and A.G.H. Visualization: B.P.B. and I.M.V. Writing - original draft: B.P.B., I.M.V., S.G.-A., Z.F., and A.G.H. Writing - review & editing: B.P.B., I.M.V., S.G.-A., Z.F., and A.G.H.

**Cite as:**

Bartholdy, B. P., Velsko, I. M., Gur-Arieh, S., Fagernäs, Z., Warinner, C., & Henry, A. G. (2023, May 30). Assessing the validity of a calcifying oral biofilm model as a suitable proxy for dental calculus. https://doi.org/10.1101/2023.05.23.541904

\normalsize

{{< pagebreak >}}

:::

::: {.content-visible when-format="html"}
{{< var article1.badges.status >}} {{< var article1.badges.version >}} {{< var article1.badges.doi >}} {{< var article1.badges.github >}}

::: {.callout-note icon="false"}

## Summary {-}

Archaeologists have been using dental calculus (or tartar) for many decades
to find traces of food from the past. What makes dental calculus so well suited
for this task is that it forms on our teeth, and is therefore in direct
contact with what we eat. It also hardens to form a strong, solid material
that can survive for long periods of time and preserve what's inside.
While we have been able to extract a lot of information from archaeological 
dental calculus, there are still many things we don't know about the context
of this information.
For example, we have no way to confirm exactly what people were eating,
we can only infer this from what we see; but, there are many factors that
influence what actually ends up in dental calculus, and it's not all food.

To address some of these issues, we have grow our own
dental calculus in a lab under controlled conditions. This will allow
us to conduct experiments to test what we see and how it relates to the
interpretations we make.
In this study, we examine our lab-grown dental calculus to make sure it
looks and behaves like naturally-occurring dental calculus, specifically
the bacterial and mineral content. We found some differences in bacterial
content, which is not uncommon for lab-grown dental plaque and calculus.
Overall, though, the lab-grown model has the makeup of
an oral microbiome, and the mineral content is very similar to natural
dental calculus.

We recommend using lab-grown models to mitigate some of the
issues we encounter when using archaeological dental
calculus to reconstruct past diets, while we also acknowledge that the model
is not a replacement for research on natural calculus, both
archaeological and modern.

:::

:::

```{r}
#| label: setup-byoc-valid
library(dplyr)
library(tidyr)
library(ggplot2)
library(stringr)
library(patchwork)
library(forcats)
library(cowplot)
library(readr)
library(here)

knitr::opts_chunk$set(fig.path = "figures/byoc-valid-")

dna_metadata <- read_tsv(here("articles/byoc-valid/01-documentation/metadata.tsv"))
dna_analysis_metadata <- read_tsv(here("articles/byoc-valid/01-documentation/analysis-metadata.tsv"))
dna_experiment_metadata <- read_tsv(here("articles/byoc-valid/01-documentation/experiment-metadata.tsv"))
bac_properties <- read_tsv(here("articles/byoc-valid/01-documentation/species-properties.tsv"))
genus_oxytol <- read_tsv(here("articles/byoc-valid/01-documentation/genus-O2tolerance.tsv"))
otu_table <- read_tsv(here("articles/byoc-valid/05-results/post-decontam_taxatable.tsv"))
pca_loadings <- readr::read_tsv(here("articles/byoc-valid/05-results/all-pca-loadings.tsv"))
load(here("articles/byoc-valid/05-results/spca_byoc.rda"))
load(here("articles/byoc-valid/05-results/spca_species.rda"))
alpha_div <- read_tsv(here("articles/byoc-valid/05-results/alpha-diversity.tsv"))
byoc_logf_full <- read_tsv(here("articles/byoc-valid/05-results/byoc_logf-full.tsv"))
plaque_logf_full <- read_tsv(here("articles/byoc-valid/05-results/plaque_logf-full.tsv"))
clr_compar_long <- readr::read_tsv(here("articles/byoc-valid/05-results/clr-compar.tsv")) %>%
  pivot_longer(-sample, values_to = "clr_count", names_to = "species")
clr_byoc_long <- readr::read_tsv(here("articles/byoc-valid/05-results/clr-byoc.tsv")) %>%
  pivot_longer(-sample, values_to = "clr_count", names_to = "species")

source(here("articles/byoc-valid/02-scripts/99_setup-qmd.R"))
source(here("articles/byoc-valid/02-scripts/99_metagen-figures.R"))

#ftir_metadata <- read_tsv(here("01-documentation/ftir-metadata.tsv"))
ftir_metadata <- read_tsv(here("articles/byoc-valid/01-documentation/ftir-metadata.tsv"))
ftir_data_raw <- read_csv(here("articles/byoc-valid/05-results/ftir-data.csv"))
ftir_grind_data <- read_csv(here("articles/byoc-valid/05-results/grind-data_cleaned.csv"))

source(here("articles/byoc-valid/02-scripts/99_tables.R"))
#source(here("02-scripts/99_figures.R"))
source(here("articles/byoc-valid/02-scripts/99_ftir-figures.R"))

# upload names and versions of software used
software_versions <- readr::read_tsv(here("articles/byoc-valid/01-documentation/software_versions.csv"), col_names = c("software", "version"))

```

## Introduction

{{< include articles/byoc-valid/07-publication/01-intro.qmd >}}

## Materials and methods

{{< include articles/byoc-valid/07-publication/02-matmet.qmd >}}

## Results

{{< include articles/byoc-valid/07-publication/03-results.qmd >}}

## Discussion

{{< include articles/byoc-valid/07-publication/04-disc.qmd >}}

## References cited
