---
engine: knitr
title: Article 2
subtitle: Investigating Biases Associated with Dietary Starch Incorporation and Retention with an Oral Biofilm Model
author: 
  - name: Bjørn Peare Bartholdy
    orcid: 0000-0003-3985-1016
    affiliations:
      - ref: leiden
  - name: Amanda G. Henry
    orcid: 0000-0002-2923-4199
    affiliations:
      - ref: leiden
affiliations:
  - id: leiden
    name: Leiden University
    department: Faculty of Archaeology
    city: Leiden
    country: The Netherlands
#shift-heading-level-by: 1
---

::: {.content-visible when-format="pdf"}

\footnotesize

**Co-authors and contributions:**

- Amanda G. Henry, Leiden University

<!-- generated with tenzing (https://rollercoaster.shinyapps.io/tenzing/) -->
Conceptualization: B.P.B. and A.G.H. Data curation: B.P.B. Formal analysis: B.P.B. Funding acquisition: A.G.H. Investigation: B.P.B. Methodology: B.P.B. and A.G.H. Resources: A.G.H. Software: B.P.B. Supervision: A.G.H. Visualization: B.P.B. Writing - original draft: B.P.B. Writing - review & editing: B.P.B. and A.G.H.

**Cite as:**

Bartholdy, B. P., & Henry, A. G. (2022). Investigating Biases Associated With Dietary Starch Incorporation and Retention With an Oral Biofilm Model. Frontiers in Earth Science, 10. https://doi.org/10.3389/feart.2022.886512

\normalsize

{{< pagebreak >}}

:::

::: {.content-visible when-format="html"}
{{< var article2.badges.status >}} {{< var article2.badges.version >}} {{< var article2.badges.doi >}} {{< var article2.badges.github >}}

::: {.callout-note icon="false"}

# Summary {-}

We used our oral biofilm model, as described in Chapter 3, to look at how starch
granules are incorporated
into dental calculus. We 'fed' the biofilm with a known quantity of starch granules
during the growth period. Preliminary results suggest that a very small proportion
of consumed starch is retained by the calculus. The size of starch granules also
influences the likelihood of retention, with larger granules less likely to be
trapped in the calculus.

:::
:::

```{r setup-starch, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  warning = FALSE,
  message = FALSE,
  #fig.path = "frontiers/figures/",
  fig.path = "figures/byoc-starch-",
  fig.align = "center",
  #fig.ext = "jpg",
  fig.pos = "H",
  dpi = 300)
library(broom)
library(here)
library(patchwork)
library(ggplot2)
#library(rticles)
devtools::load_all("articles/byoc-starch/")

plt1_ph1 <- readr::read_tsv(
  here("articles/byoc-starch/analysis/data/raw_data/ExpM_plate1_photometric1.csv"),
  col_names = F)
plt1_ph2 <- readr::read_tsv(
  here("articles/byoc-starch/analysis/data/raw_data/ExpM_plate1_photometric2.csv"),
  col_names = F)

plt2_ph1 <- readr::read_tsv(
  here("articles/byoc-starch/analysis/data/raw_data/ExpM_plate2_photometric1.csv"),
  col_names = F)
plt2_ph2 <- readr::read_tsv(
  here("articles/byoc-starch/analysis/data/raw_data/ExpM_plate2_photometric2.csv"),
  col_names = F)
# starch counts in samples
raw_counts <- readr::read_csv(here("articles/byoc-starch/analysis/data/raw_data/starch_counts.csv"))
# starch counts in solutions
sol_counts <- readr::read_csv(here("articles/byoc-starch/analysis/data/raw_data/solution_counts.csv"))
# load R scripts
source(here("articles/byoc-starch/analysis/scripts/analysis.R"))
source(here("articles/byoc-starch/analysis/scripts/tables.R"))
source(here("articles/byoc-starch/analysis/scripts/figures.R"))
source(here("articles/byoc-starch/analysis/scripts/amylase-assay.R"))
#readr::write_csv(sol_corr, here("articles/byoc-starch/analysis/data/derived_data/sol_corr.csv"))
#readr::write_csv(corr_counts, here("articles/byoc-starch/analysis/data/derived_data/corr_counts.csv"))
#readr::write_csv(corr_comb, here("articles/byoc-starch/analysis/data/derived_data/corr_comb.csv"))


cor_r <- signif(count_cor$estimate, 3)
cor_ci <- signif(count_cor$conf.int, 3)
cor2_r <- signif(count_cor$estimate, 3)
cor2_ci <- signif(count_cor$conf.int, 3)
```

## Introduction {#byocstarch-intro}

{{< include articles/byoc-starch/analysis/paper/intro.qmd >}}

## Materials and Methods

{{< include articles/byoc-starch/analysis/paper/matmet.qmd >}}

## Results

{{< include articles/byoc-starch/analysis/paper/results.qmd >}}

## Discussion

{{< include articles/byoc-starch/analysis/paper/discussion.qmd >}}

## Conclusion

{{< include articles/byoc-starch/analysis/paper/conclusion.qmd >}}

## References cited {.unnumbered}
