---
engine: knitr
title: Article 3
subtitle: Multiproxy analysis exploring patterns of diet and disease in dental calculus and skeletal remains from a 19th century Dutch population
author: 
  - name: Bjørn Peare Bartholdy
    orcid: 0000-0003-3985-1016
    affiliations:
      - ref: leiden
  - name: Jørgen B. Hasselstrøm
    affiliations: 
      - ref: aarhus
  - name: Lambert K. Sørensen
    affiliations: 
      - ref: aarhus
  - name: Maia Casna
    affiliations: 
      - ref: leiden
  - name: Menno Hoogland
    affiliations:
      - ref: leiden
  - name: Historisch Genootschap Beemster
    url: https://historischgenootschapbeemster.nl/
    affiliations:
      - ref: hgb
  - name: Amanda G. Henry
    orcid: 0000-0002-2923-4199
    affiliations:
      - ref: leiden
affiliations:
  - id: leiden
    name: Leiden University
    #department: Faculty of Archaeology
    #city: Leiden
    country: The Netherlands
  - id: aarhus
    name: Department of Forensic Medicine, Aarhus University
    #address: Palle Juul-Jensens Boulevard 99, 8200, Aarhus N, Denmark
  - id: hgb
    name: Historisch Genootschap Beemster
    #address: Postbus 73, 1462 ZH, Middenbeemster, Netherlands
#shift-heading-level-by: 1
---

:::{.content-visible when-format="pdf"}

\footnotesize

**Co-authors and contributions:**

- Jørgen B. Hasselstrøm, Aarhus University
- Lambert K. Sørensen, Aarhus University
- Maia Casna, Leiden University
- Menno Hoogland, Leiden University
- Historisch Genootschap Beemster
- Amanda G. Henry, Leiden University

<!-- generated with tenzing (https://rollercoaster.shinyapps.io/tenzing/) -->

Conceptualization: B.P.B., J.B.H., L.K.S., and A.G.H.
Data curation: B.P.B. Formal analysis: B.P.B., J.B.H., L.K.S., and M.C.
Funding acquisition: A.G.H.
Investigation: B.P.B. and H.G.B.
Methodology: B.P.B., J.B.H., L.K.S., and M.C.
Resources: J.B.H., L.K.S., and M.H.
Software: B.P.B.
Supervision: A.G.H.
Visualization: B.P.B.
Writing - original draft: B.P.B. and M.C.
Writing - review \& editing: B.P.B., J.B.H., L.K.S., M.C., M.H., H.G.B., and A.G.H.

**Cite as:**

Bartholdy, B. P., Hasselstrøm, J. B., Sørensen, L. K., Casna, M., Hoogland, M., Beemster, H. G., & Henry, A. G. (2024).
Multiproxy analysis exploring patterns of diet and disease in dental calculus and skeletal remains from a 19th century
Dutch population. Peer Community Journal, 4. https://doi.org/10.24072/pcjournal.414

\normalsize

{{< pagebreak >}}


:::

::: {.content-visible when-format="html"}
{{< var article3.badges.status >}} {{< var article3.badges.version >}} {{< var article3.badges.doi >}} {{< var article3.badges.github >}}

::: {.callout-note icon="false"}

## Summary {.unnumbered}

We used a fancy chemical method to find different types of food
and possible medicine
in dental calculus from, Middenbeemster, a rural 19th century
archaeological population in the Netherlands. 

:::
:::

```{r}
#| label: setup
#| include: false
#| cache: false

library(here)
library(readr)
devtools::load_all("articles/mb11CalculusPilot")

# upload data
metadata <- read_tsv(here("articles/mb11CalculusPilot/analysis/data/raw_data/metadata.tsv"))
demography <- read_csv(here("articles/mb11CalculusPilot/analysis/data/raw_data/demography.csv"))
lloq <- read_tsv(here("articles/mb11CalculusPilot/analysis/data/raw_data/lloq.tsv"))
uhplc_data_comb <- read_csv(here("articles/mb11CalculusPilot/analysis/data/derived_data/uhplc-data_combined.csv"))
dental_inv <- read_csv(here("articles/mb11CalculusPilot/analysis/data/raw_data/dental-inv.csv"))
caries <- read_csv(here("articles/mb11CalculusPilot/analysis/data/raw_data/caries.csv"))
periodont <- read_csv(here("articles/mb11CalculusPilot/analysis/data/raw_data/periodontitis.csv"))
periap <- read_csv(here("articles/mb11CalculusPilot/analysis/data/raw_data/periapical.csv"))
#calculus <- read_csv(here("analysis/data/raw_data/calculus.csv"))
calculus_full <- read_csv(here("articles/mb11CalculusPilot/analysis/data/raw_data/calculus_full.csv"))
sinusitis_clean <- read_csv(here("articles/mb11CalculusPilot/analysis/data/derived_data/sinusitis_cleaned.csv"))
path_cond_clean <- read_csv(here("articles/mb11CalculusPilot/analysis/data/derived_data/path-conditions_cleaned.csv"))

source(here("articles/mb11CalculusPilot/analysis/scripts/setup-qmd.R"))
#source(here("analysis/supplementary-materials/supp-mat.qmd"), local = knitr::knit_global())
# set viridis as default pallette

options(ggplot.discrete.colour = function() scale_fill_viridis_d())
```

## Introduction {#mb11CalculusPilot}

{{< include articles/mb11CalculusPilot/analysis/paper/_intro.qmd >}}

## Materials {#mb11CalculusPilot-mat}

{{< include articles/mb11CalculusPilot/analysis/paper/_materials.qmd >}}

## Methods

{{< include articles/mb11CalculusPilot/analysis/paper/_methods.qmd >}}

## Results

{{< include articles/mb11CalculusPilot/analysis/paper/_results.qmd >}}

## Discussion

{{< include articles/mb11CalculusPilot/analysis/paper/_discussion.qmd >}}

## Conclusion

{{< include articles/mb11CalculusPilot/analysis/paper/_conclusions.qmd >}}

## References cited {.unnumbered}
