# Summary {.unnumbered}

<!-- Dental calculus -->

Dental calculus. This small, hard, inconspicuous substance that forms on the
teeth of humans and animals contains a surprising amount of information about our
lives. During formation and growth as a living plaque biofilm, it tends to
accumulate a wide variety of very small particles, especially bacteria and food
debris, from various sources. 
These sources and
the particles they leave behind in our mouth are influenced by activities and
biological processes that are unique to us, such as our dietary preferences,
oral hygiene practices, genetics, and the environment in which we live.
<!-- archaeological dental calculus -->
What makes it so interesting to archaeologists is that, following mineralisation,
these particles become trapped and
well-protected against removal and degradation during hundreds to thousands of
years in the ground, preserving a picture of the activities performed by its
human host. This picture can be unlocked by archaeologists by extracting and
identifying proteins from plants and animals, and genetic material and microremains
from plants that were trapped inside the calculus matrix.
<!-- Problem formulation -->
The major problem—one of the major problems, for there are several—one of the many
major problems is that this picture was never a complete picture of a lifetime of
activities. Another problem is that it has faded over the years, and some parts of
the picture have been completely erased. There are many things influencing what
gets trapped inside dental calculus, what gets preserved for all those years until
it can be analysed, and how much of that information we can extract and interpret.
<!-- research questions -->
We know that these problems exist. We know that they limit our interpretations of
past activities. We need to approach these problems more systematically at a
fundamental level. 

We need to find out more
about what exactly is causing external particles to become trapped inside our
dental calculus, and be able to quantify exactly how they impact our interpretations
of dietary practices from archaeological dental calculus.

My dissertation introduces a potential method for resolving these issues, namely
a protocol for growing artificial dental calculus in a lab. Working with a very
controlled model of dental calculus in a lab allows me
to explore the influence of a wide range of factors that may influence the uptake
of particles into dental calculus, and what biases are introduced by these factors
as well as the methods we currently use to extract information from archaeological
dental calculus. Addressing these fundamental issues and limitations will go a
long way towards improving the resolution of our interpretations of past dietary
activities. I also explore new ways to extract information from archaeological
dental calculus to learn more about our past.

<!-- summary of dissertation chapters -->
**Chapter 1** is a brief introduction into the many uses of
archaeological dental calculus to reconstruct the diet of past populations.
I also outline the current state of dental calculus research, and some of the
problems we are facing. I only briefly describe what dental calculus is, and
how it is formed; this is an important concept to understand, since it influences
the uptake of food particles, and is influenced by diet. **Chapter 2** provides
more detail on the formation and growth of dental plaque, and mineralisation
to form dental calculus. Here, I also provide an overview of oral biofilm models
to provide some context for the experiments I conducted in my dissertation research
using an oral biofilm model

**Chapter 3** is the first article, which introduces
the oral biofilm model I developed for my research. In this article we also
assess the ability of our model to mimic the properties of natural dental calculus
in order to justify using model calculus as a proxy for archaeological dental
calculus. By characterising the bacteria present in the model calculus,
<!-- elaborate on method - sequencing the DNA and identifying species abundances-->
we found
that it was indicative of an oral microbiome, though somewhat distinct from the
natural calculus we used as a comparison. We also determined the mineral content
using Fourier Transform Infrared (FTIR) spectroscopy, which established that the
model was primarily made up of carbonate hydroxyapatite, the predominant mineral
in natural dental calculus. The second article that forms **Chapter 4** we applied
the calculus model to find out what happens when we add a known amount of
dietary starch granules to model calculus during formation, and attempt to extract
the starches using a common method for extraction of starches from archaeological
dental calculus. We were able to validate what previous studies on modern humans
and non-human primates have shown, that the quantity of starches that we extract
from calculus, is not very representative of the dietary intake.
We also discovered that one of the causes for this misrepresentation of the starch
record is that large starch granules were being incorporated at a lower rate
than smaller granules. This was demonstrated by the fact that potato granules,
which are quite a bit larger than wheat, were underrepresented in our extracted
counts.

In addition to diving into the causes behind dental calculus limitations, we also
sought out to find novel uses for archaeological dental calculus. In **Chapter 5**,
the final article in this dissertation, we used a novel method employing
ultra high performance liquid chromatography-tandem mass spectrometry
(UHPLC-MS/MS) to identify various plant-based alkaloids traditionally used
for medication and non-dietary activities, such as nicotine, opioids, and
cannabinoids.
We were unable to detect opioids and cannabinoids, but
we found evidence of alkaloids and metabolites derived from the consumption of
tea and/or coffee, as well as nicotine (and its metabolite, cotinine), and
salicylic acid, the primary phytohormone in willow bark. 
 We combined these results with the presence of skeletal and dental
indicators of disease to find patterns of potential disease management.
We were unable to
definitively link the presence of these with evidence of disease to justify
medicinal activities, but we found some interesting correlations between
maxillary sinusitis and markers of tobacco-use and consumption of tea and coffee.

In the final part of the dissertation, **Chapter 6**, I discuss the outcomes of
the studies from previous chapters, addressing the oral biofilm model and its
implications for archaeological research. I lay out the challenges we need to
accept to further our understanding of archaeological dental calculus and how it
relates to the dietary activities of the people we study in the past. This includes
systematically conducting more fundamental research to understand the mechanisms
causing various dietary (and non-dietary) markers to become entrapped in dental
calculus.


# Samenvatting {.unnumbered}

*Translation by Esther Plomp*

Tandsteen. Deze kleine, harde, onopvallende substantie vormt op de tanden van mensen en dieren. Tandsteen bevat verrassend veel informatie over ons leven. Tijdens de vorming en groei is tandsteen een levende biofilm plak en neemt het een grote verscheidenheid aan zeer kleine deeltjes op uit verschillende bronnen, met name bacteriën en voedselresten. Deze bronnen, en de deeltjes die ze achterlaten in onze mond, worden beïnvloed door activiteiten en biologische processen die uniek zijn voor elke persoon, dankzij onze eetgewoonten, mondhygiëne, genetica en de omgeving waarin we leven.

Wat het zo interessant maakt voor archeologen is dat deze deeltjes ingebed zijn in het tandsteen na de mineralisatie van de tandplak. Hierdoor zijn de deeltjes goed beschermd zijn tegen verwijdering en afbraak gedurende honderden tot duizenden jaren in de bodem, waardoor zij een beeld kunnen geven van de activiteiten van de mens. Archeologen kunnen dit beeld ontrafelen door eiwitten van planten en dieren, evenals genetisch materiaal en microresten van planten die gevangen zitten in de kalkmatrix, te extraheren en te identificeren.

Het grote probleem - of één van de grote problemen, want er zijn meerdere - is dat dit beeld nooit een compleet beeld is van een leven vol activiteiten. Een ander probleem is dat het beeld in de loop der jaren vervaagd en dat sommige delen volledig uitgewist zijn. Er zijn veel dingen van invloed op wat ingebed raakt in tandsteen, wat er al die jaren bewaard blijft, en hoe het tandsteen geanalyseerd kan worden. Dit heeft invloed op de hoeveelheid informatie die we uit tandsteen kunnen verkrijgen en op de manier waarop we deze informatie interpreteren.

We weten dat deze problemen bestaan. We weten dat ze onze interpretaties van activiteiten in het verleden beïnvloeden. Het is noodzakelijk om deze problemen op een meer systematische wijze op een fundamenteel niveau aan te pakken. Hoe raken externe deeltjes precies vast in ons tandsteen? Ook moeten we preciezer kunnen kwantificeren welke factoren onze interpretaties van voedingsgewoontes beïnvloeden. 

Mijn proefschrift introduceert een potentiële methode om deze problemen op te lossen. Deze methode bestaat uit een protocol voor het kweken van kunstmatig tandsteen in een laboratorium (model tandsteen). Door te werken met een gecontroleerd model van tandsteen in een laboratorium kunnen een breed scala aan invloeden op tandsteen onderzocht worden. Bijvoorbeeld de factoren die van invloed zijn op de opname van deeltjes in tandsteen, welke vertekeningen hierdoor worden geïntroduceerd, evenals de invloed van methoden die we momenteel gebruiken om informatie te halen uit archeologische tandsteen. 

Het aanpakken van deze fundamentele problemen en beperkingen zal de resolutie van onze interpretaties van eetgewoonten in het verleden
verbeteren. Ik onderzoek ook nieuwe manieren om informatie uit archeologische tandsteen te onttrekken om zo meer te weten te komen over ons verleden.

**Hoofdstuk 1** is een korte introductie over de vele toepassingen van archeologische tandsteen om het dieet van vroegere populaties te reconstrueren.
Ook schets ik de huidige stand van het tandsteenonderzoek, onder andere enkele de problemen waarmee we worden geconfronteerd. Ik beschrijf slechts kort wat tandsteen is en hoe het wordt gevormd. De vorming van tandsteen heeft invloed op de opname van voedseldeeltjes, en wordt tegelijkertijd ook beïnvloed door het dieet. **Hoofdstuk 2** biedt meer details over de vorming en groei van tandplak en het mineralisatie proces van tandsteen. Hier geef ik ook een overzicht van orale biofilmmodellen om enige context te bieden voor de experimenten met oraal biofilmmodel die ik heb uitgevoerd in mijn proefschriftonderzoek.

**Hoofdstuk 3** is het eerste artikel waarin het orale biofilmmodel wordt geïntroduceerd dat ik voor mijn onderzoek heb ontwikkeld. In dit artikel beoordelen we het vermogen van ons model tandsteen om de eigenschappen van natuurlijke tandsteen na te bootsen. Hierdoor zou het model als proxy kunnen dienen voor archeologisch tandsteen. Door de bacteriën in het model te karakteriseren, vonden we dat het model indicatief was voor het microbioom in de mond (alhoewel enigszins verschillend van natuurlijk tandsteen). We bepaalden ook het mineraalgehalte met behulp van Fourier Transform Infrared (FTIR) spectroscopie, waarmee we vaststelden dat het model voornamelijk bestond uit hydroxyapatietcarbonaat, het overheersende mineraal in natuurlijk tandsteen. 

In het tweede artikel dat **Hoofdstuk 4** vormt, pasten we het calculusmodel toe om uit te zoeken wat er gebeurt als we een bekende hoeveelheid zetmeelkorrels toevoegen aan het model tandsteen tijdens de vorming van tandsteen. We probeerden de zetmeel korrels te extraheren met behulp van een gebruikelijke methode voor het extraheren van korrels uit archeologische tandsteen. We waren in staat om te valideren wat eerdere studies op moderne mensen en niet-menselijke primaten al hebben aangetoond, namelijk dat de hoeveelheid zetmeel in tandsteen niet representatief is voor de voedselinname. Dit komt omdat grotere zetmeel korrels langzamer worden opgenomen in vergelijking met kleinere korrels. Zo waren aardappelkorrels, die een stuk groter zijn dan tarwekorrels, ondervertegenwoordigd in onze geëxtraheerde tellingen.

Naast het onderzoeken van de oorzaken achter de beperkingen van tandsteen analyses, hebben we ook gezocht naar nieuwe toepassingen voor archeologische tandsteen. In **Hoofdstuk 5**, het laatste artikel in dit proefschrift, gebruikten we een nieuwe methode met ultrahoge prestatie vloeistofchromatografie-tandem massaspectrometrie (UHPLC-MS/MS) om verschillende alkaloïden op basis van planten te identificeren die traditioneel worden gebruikt voor medicatie en activiteiten die niet gerelateerd zijn aan het dieet (zoals nicotine, opioïden en cannabinoïden).
We konden opioïden en cannabinoïden niet detecteren, maar we vonden wel bewijs van alkaloïden en metabolieten afkomstig van de consumptie van thee en/of koffie, evenals nicotine (en de metaboliet daarvan, cotinine), en salicylzuur (het primaire fytohormoon in wilgenbast).
We combineerden deze resultaten met de aanwezigheid van skelet- en tandheelkundige indicatoren van ziekte om zo patronen te vinden van mogelijke ziekte behandelingen.
We waren niet in staat om een definitief verband te leggen tussen ziektes en medicinale activiteiten, maar we vonden wel enkele interessante correlaties tussen sinusitis maxillaris en tabaksgebruik en thee- en koffieconsumptie.

In het laatste deel van het proefschrift, **Hoofdstuk 6**, bespreek ik de uitkomsten van de studies uit voorgaande hoofdstukken, waarbij ik inga op het orale biofilmmodel en de implicaties ervan voor archeologisch onderzoek. 
Ik beschrijf de uitdagingen die we moeten aangaan om ons begrip van archeologische tandsteen te vergroten om zo het dieet van de mens in het verleden beter te kunnen bestuderen. 
Dit vereist het systematisch uitvoeren van fundamenteler onderzoek om de onderliggende mechanismen beter te begrijpen waardoor verschillende voedingsmarkers (en niet-dieetmarkers) ingebed worden in tandsteen.
