# example R options set globally
options(width = 60)

# example chunk options set globally
knitr::opts_chunk$set(
  comment = "#>",
  collapse = TRUE
  )

#library(here)
# refs <- rbbt::bbt_detect_citations()
# bbtignore <- c("R-bookdown", "R-base")
# rbbt::bbt_write_bib(here("book.bib"), keys = refs, ignore = bbtignore, overwrite = T, translator = "bibtex")
#NOTE: latex bib compiler does not like the 'date' entry of .bib file generated by rbbt
# article1_bib <- rbbt::bbt_detect_citations("02-article1.Rmd")
# rbbt::bbt_write_bib("article-1.bib", keys = article1_bib, overwrite = T, translator = "bibtex")
#rbbt::bbt_update_bib(here("index.Rmd"), here("book.bib"))
