project:
  type: book
  pre-render: _common.R # causes issue with quarto preview - issue caused by `bbt_update_bib(ref_files, here("book.bib"))`

book:
  title: "Putting Dental Calculus Under the Microscope"
  subtitle: ""
  author: "Bjørn Peare Bartholdy"
  date: last-modified
  date-format: iso
  output-file: "endgame"
  cover-image: cover.png # path to the social sharing image like images/cover.jpg
  downloads: pdf
  description: "This is, or rather, this will be a PhD dissertation"
  repo-url: "https://github.com/bbartholdy/endgame"
  site-url: "https://myphd.netlify.app"
  page-footer: 
    left: |
      *Putting Dental Calculus Under the Microscope* was written by Bjørn Peare Bartholdy. It was last built on {{< meta date >}}.
    right: 
    - icon: github
      href: https://github.com/bbartholdy
    - icon: twitter 
      href: https://twitter.com/osteobjorn
  chapters: 
    - index.qmd
    - 01-intro.Rmd
    - 02-background.Rmd
    - 03-article.qmd
    - 04-article.Rmd
    #- 05-article.Rmd
    - 06-discussion.Rmd

format:
  html:
    theme: 
      light: [lightly, style.scss]
      dark: [darkly, style.scss]
    reference-location: section
    include-in-header: partials/analytics.html
    #citeproc: true
    bibliography: [book.bib]
    #filters: 
    #- section-refs.lua

  pdf:
    documentclass: book
    block-headings: false # needed for titlesec to work
    lot: true
    lof: true
    #pdf-engine: latexmk
    keep-tex: true
    cite-method: citeproc
    section-refs-bibliography: book.bib
    template: latex/default.latex
    #template: pandoc-templates/default.latex
    #include-before-body: latex/proef.tex
    include-in-header: latex/preamble.tex
    filters: 
      - section-refs.lua # needs pandoc version >= 2.11 to work 
    
# link-citations: yes
csl: apa.csl
knitr:
  opts_chunk: 
    collapse: true
    comment: "#>"
    echo: false
    message: false
    warning: false
### Mandatory for Leiden PhD dissertations ###
proefschrift:
  rector: Dr. H.J. Farnsworth # name of current rector
  day: Wednesday # day of week
  date: "21 March 3020" # date in dd month yyyy format
  time: "13.00" # time in 00.00 format
  birthplace: "Earth" # optional info
  birthyear: "the 20th century" # optional info
promotor:
  name: Dr. Amanda G. Henry
copromotor:
  name: Dr. Annelou van Gijn
    #affiliation: required if different from Leiden
committee:
  - name: Dr. Bernadette Rostenkowski-Wolowitz
    affiliation: ZanGen Pharmaceuticals
  - name: Dr. Amy Farrah Fowler
    affiliation: California Institute of Technology
  - name: Dr. Sheldon Cooper
    affiliation: California Institute of Technology
  - name: Dr. Leonard Hofstadter
    affiliation: California Institute of Technology
## End: Mandatory for Leiden PhD dissertations ###
funding: |
  This research has received funding from the European Research Council under the European Union’s Horizon 2020 research and innovation program, grant agreement   number STG–677576 (“HARVEST”).
# #quote:
#   # quote: Random quote only meaningful to me   # can also be used for a dedication
# #  source: Someone old
