project:
  type: book
  pre-render: _common.R
execute:
  freeze: auto
  echo: false
  warning: false

book:
  title: "Putting Dental Calculus Under the Microscope"
  subtitle: ""
  author: "Bjørn Peare Bartholdy"
  date-format: "DD-MMM-YYYY"
  output-file: "endgame"
  cover-image: cover.jpg # path to the social sharing image like images/cover.jpg
  cover-image-alt: |
    The image depicts a tooth with a layer of dental calculus around the crown.
    A magnifying glass is placed over some of the dental calculus and gives us a
    look at some cartoonish-looking bacteria eating starch granules.
  downloads: pdf
  description: "This is, or rather, this will be a PhD dissertation"
  repo-url: "https://github.com/bbartholdy/endgame"
  site-url: "https://myphd.netlify.app"
  page-footer: 
    left: |
      *Putting Dental Calculus Under the Microscope* was written by {{< meta book.author >}}. It was last built on {{< meta format.html.date-modified >}}.
    right: 
    - icon: github
      href: https://github.com/bbartholdy
    - icon: mastodon 
      href: https://fediscience.org/@bjorn
  chapters: 
    - index.qmd
    - 01-intro.qmd
    - 02-background.qmd
    - 03-article.qmd
    - 04-article.qmd
    - 05-article.qmd
    - 06-discussion.qmd
  #appendices:
    - supp-mat.qmd
    - 98-summary.qmd
    - 99-cv.qmd

format:
  html:
    theme: 
      light: [lightly, style.scss]
      dark: [darkly, style.scss]
    date-modified: today
    #date: "2024-05-03" date of print?
    include-after-body: partials/analytics.html

  pdf:
    documentclass: book
    papersize: b5
    mainfont: AtkinsonHyperlegible
    mainfontoptions: 
      - Path=./font/ttf/
      - Extension=.ttf
      - UprightFont=*-Regular
      - BoldFont=*-Bold
      - ItalicFont=*-Italic
      - BoldItalicFont=*-BoldItalic
    block-headings: false # needed for titlesec (preamble.tex) to work
    linestretch: 1.24
    lot: true
    lof: true
    keep-tex: true
    citeproc: false
    link-citations: true
    pdf-engine: xelatex
    #pdf-engine-opt: -xelatex
    #template: pandoc-templates/default.latex
    include-in-header: latex/preamble.tex
    include-before-body: latex/dedication.tex
    filters: 
      - section-bibliographies

bibliography: book.bib
reference-location: section
csl: apa.csl
knitr:
  opts_chunk: 
    collapse: true
    comment: "#>"
    message: false
### Mandatory for Leiden PhD dissertations ###
proefschrift:
  rector: prof.dr.ir. H. Bijl # name of current rector
  day: Donderdag # day of week
  date: "30 Mei 2024" # date in dd month yyyy format
  time: "11.15" # time in 00.00 format
  #birthplace: "Earth" # optional info
  #birthyear: "the 20th century" # optional info
promotor:
  name: Dr. Amanda G. Henry
copromotor:
  name: Prof.dr. Annelou van Gijn
    #affiliation: required if different from Leiden
committee:
  - name: Prof.dr. Patrick Degryse
    affiliation: 
      - Leiden University
      - Katholieke Universiteit Leuven
  - name: Prof.dr. Matthew James Collins
    affiliation: 
      - University of Copenhagen
      - University of Cambridge
  - name: Dr. Alison Crowther
    affiliation: University of Queensland
  - name: Prof.dr. Carla Lancelotti
    affiliation: Universitat Pompeu Fabra and ICREA
  - name: Dr. Christina Warinner
    affiliation: 
      - Max Planck Institute for Evolutionary Anthropology
      - Harvard University
## End: Mandatory for Leiden PhD dissertations ###
funding-statement: |
  This research has received funding from the European Research Council under the European Union's Horizon 2020 research and innovation program, grant agreement number STG–677576 (“HARVEST”).
cover-caption: Design by Krijn Boom and image by Petra Korlevic
printed-by: Gildeprint
print-version: "[2024.04.1](https://doi.org/10.5281/zenodo.11077009)"
