project:
  type: book
  pre-render: _common.R
execute:
  freeze: auto
  echo: false
  warning: false

book:
  title: "Putting Dental Calculus Under the Microscope"
  subtitle: ""
  author: "Bjørn Peare Bartholdy"
  #date: last-modified
  date-format: "DD-MMM-YYYY"
  output-file: "endgame"
  cover-image: cover.png # path to the social sharing image like images/cover.jpg
  cover-image-alt: |
    The image depicts a tooth with a layer of dental calculus around the crown.
    A magnifying glass is placed over some of the dental calculus and gives us a
    look at some cartoonish-looking bacteria eating starch granules.
  downloads: pdf
  description: "This is, or rather, this will be a PhD dissertation"
  repo-url: "https://github.com/bbartholdy/endgame"
  site-url: "https://myphd.netlify.app"
  page-footer: 
    left: |
      *Putting Dental Calculus Under the Microscope* was written by {{< meta book.author >}}. It was last built on {{< meta format.html.date-modified >}}.
    right: 
    - icon: github
      href: https://github.com/bbartholdy
    - icon: mastodon 
      href: https://fediscience.org/@bjorn
  chapters: 
    - index.qmd
    #- 00-awknowledgements.qmd
    #- 00-preface.qmd
    - 01-intro.qmd
    - 02-background.qmd
    - 03-article.qmd
    - 04-article.qmd
    - 05-article.qmd
    - 06-discussion.qmd
  appendices:
    - supp-mat.qmd
    - 98-summary.qmd
    - 99-cv.qmd

format:
  html:
    theme: 
      light: [lightly, style.scss]
      dark: [darkly, style.scss]
    date-modified: today
    #reference-location: section
    #include-in-header: partials/analytics.html
    include-after-body: partials/analytics.html
    #citeproc: true
    #bibliography: [book.bib]

  pdf:
    documentclass: book
    block-headings: false # needed for titlesec (preamble.tex) to work
    lot: true
    lof: true
    keep-tex: true
    #cite-method: citeproc
    citeproc: false
    link-citations: true
    #bibliography: [book.bib]
    #section-refs-bibliography: [book.bib, articles/byoc-starch/analysis/paper/refs.bib, articles/mb11CalculusPilot/analysis/paper/references.bib]
    template: pandoc-templates/default.latex
    #include-before-body: latex/dedication.tex
    include-in-header: latex/preamble.tex
    filters: 
      - section-bibliographies
      #- section-refs.lua # needs pandoc version >= 2.11 to work 
      #- shift-article-headings.lua

bibliography: book.bib
#cite-method: citeproc
reference-location: section
csl: apa.csl
knitr:
  opts_chunk: 
    collapse: true
    comment: "#>"
    message: false
### Mandatory for Leiden PhD dissertations ###
proefschrift:
  rector: prof.dr.ir. H. Bijl # name of current rector
  day: TBD # day of week
  date: "" # date in dd month yyyy format
  time: "TBD" # time in 00.00 format
  #birthplace: "Earth" # optional info
  #birthyear: "the 20th century" # optional info
promotor:
  name: Dr. Amanda G. Henry
copromotor:
  name: Dr. Annelou van Gijn
    #affiliation: required if different from Leiden
committee:
  - name: Dr. Patrick Degryse
    affiliation: Leiden University, Katholieke Universiteit Leuven
  - name: Dr. Matthew James Collins
    affiliation: University of Copenhagen, University of Cambridge
  - name: Dr. Alison Crowther
    affiliation: University of Queensland
  - name: Dr. Carla Lancelotti
    affiliation: Universitat Pompeu Fabra and ICREA
  - name: Dr. Christina Warinner
    affiliation: Max Planck Institute for Evolutionary Anthropology, Harvard University
## End: Mandatory for Leiden PhD dissertations ###
funding-statement: |
  This research has received funding from the European Research Council under the European Union’s Horizon 2020 research and innovation program, grant agreement number STG–677576 (“HARVEST”).
cover-caption: Petra Korlevic
