project:
  type: book

book:
  title: "Putting Dental Calculus Under the Microscope"
  subtitle: ""
  author: "Bjørn Peare Bartholdy"
  date: Unpublished
  output-file: "endgame"
  cover-image: cover.png # path to the social sharing image like images/cover.jpg
  downloads: pdf
  chapters: 
    - index.qmd
    - 01-intro.qmd

### FROM _bookdown.yml ###
# book_filename: "endgame"
# new_session: true
# before_chapter_script: _common.R
# delete_merged_file: true
# language:
#   ui:
#     chapter_name: ""
# rmd_files: [
#     "index.Rmd",
#     "01-intro.Rmd",
#     "02-background.Rmd",
#     "03-article.Rmd",
#     "04-article.Rmd",
#     "05-article.Rmd",
#     "06-discussion.Rmd",
#     "07-references.Rmd",
#     "08-backmatter.Rmd"
#     ]

### FROM _output.yml ###
# bookdown::bs4_book:
#   #css: bs4_style.css
#   includes:
#     in_header: partials/analytics.html
#   keep_md: yes
#   theme:
#     primary: "#782386"
#     secondary: "#d1295a"
#   split_bib: yes # per-chapter bibliography
#   repo:
#     base: https://github.com/bbartholdy/endgame
#     branch: main
# # bookdown::gitbook:
# #   css: css/style.css
# #   config:
# #     toc:
# #       before: |
# #         <li><a href="./">Dissertation Title</a></li>
# #       after: |
# #         <li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>
# #     edit: https://github.com/bbartholdy/endgame/edit/main/%s
# #     download: ["pdf", "epub"]
# bookdown::pdf_book:
#   template: latex/default.latex
#   includes:
#     in_header: latex/preamble.tex
#   latex_engine: xelatex
#   citation_package: biblatex
#   #citation_package: natbib
#   keep_tex: yes
# #bookdown::epub_book: default
  
format:
  html:
    theme: [cosmo, style.scss]
    
  pdf:
    documentclass: scrbook
    pdf-engine: xelatex
    cite-method: citeproc
    filters: 
      - section-refs.lua
    
bibliography: book.bib

# ### Mandatory for Leiden PhD dissertations ###
# proefschrift: 
#   rector: Dr. H.J. Farnsworth # name of current rector
#   day: Wednesday # day of week
#   date: "21 March 3020" # date in dd month yyyy format
#   time: "13.00" # time in 00.00 format
#   birthplace: "Halifax" # optional info
#   birthyear: 1988 # optional info
# promotor: 
#   name: Dr. Amanda G. Henry
# copromotor: 
#   - name: Dr. Annelou van Gijn
#     #affiliation: required if different from Leiden
# committee: 
#   - name: Dr. Bernadette Rostenkowski-Wolowitz
#     affiliation: ZanGen Pharmaceuticals
#   - name: Dr. Amy Farrah Fowler
#     affiliation: California Institute of Technology
#   - name: Dr. Sheldon Cooper
#     affiliation: California Institute of Technology
#   - name: Dr. Leonard Hofstadter
#     affiliation: California Institute of Technology
# ## End: Mandatory for Leiden PhD dissertations ###
# funding: |
#   This research has received funding from the European Research Council under the European Union’s Horizon 2020 research and innovation program, grant agreement   number STG–677576 (“HARVEST”).
# #quote:
#   # quote: Random quote only meaningful to me   # can also be used for a dedication
# #  source: Someone old
# site: bookdown::bookdown_site
# documentclass: book
# bibliography: [book.bib, packages.bib]
# #biblio-style: apalike
# #biblio-style: authoryear
# biblatexoptions: [natbib, style=apa,refsection=chapter]
# #reference-section-title: References
# suppress-bibliography: false
# csl: apa.csl
# link-citations: yes
# url: https://myphd.netlify.app # your book url
# github-repo: bbartholdy/endgame
# description: "This is, or rather, this will be a PhD dissertation"
# lof: true
# lot: true