::: {.content-visible when-format="html"}

# Hello {-}

This is a PhD dissertation written in [Quarto](https://quarto.org/). A PDF version of the dissertation, which
includes a variety of trivial formalities, is available [here](https://myphd.netlify.app/endgame.pdf)<!-- and here (doi to repo)-->.
In the meantime you can follow the progress of my dissertation on this site.

**Note: This is a continuously updated draft of my dissertation (until further notice). It has yet to be reviewed by a committee.**

The amazing cover image was created by the awesome
[Petra Korlevic](https://twitter.com/petrathepostdoc). The site is hosted by [Netlify](https://www.netlify.com)
and [GitHub](https://www.github.com), and is licensed under the
[Creative Commons Attribution 4.0 International License](https://creativecommons.org/licenses/by/4.0/).

**Disclaimer:** This site contains a bare-bones tracker to count the number of
visitors. No other information is recorded.

:::

::: {.content-visible when-format="pdf"}
\frontmatter

# Acknowledgements {-}

Where to begin? So many people helped shape this thesis, and are therefore also 
to blame for this work.

<!-- Amanda -->

<!-- Shira -->

<!-- Stephanie -->

<!-- James and Zandra 

James Fellows Yates and Dr. Zandra Fagernäs were always able to reignite my
excitement for the project when I occasionally felt it slipping away. Their
enthusiasm was always appreciated. James was also an important contributor
to the main biofilm model paper, as I struggled to implement the EAGER pipeline,
not to mention an inspiration on how to PhDad.

<!-- Irina -->

<!-- Open Science 

Dr. Ben Marwick and Dr. Esther Plomp, whose passion and commitment to open science
inspired me to make all of my work as open and transparent as possible. This also
likely contributed to some of the delays, so thanks for that.

<!-- Middenbeemster historical society -->

<!-- Danish lab -->

<!-- Jessica and Rachel -->

<!-- Supriya and Nina 

Supriya and Nina for having the patience to be friends with a PhD student with a small child.

<!-- family 

Of course, I have to include my family, since they are the most likely to read this.

And finally, most importantly, Liam, for making everything a bit more of a challenge,
-->

:::

# Open Science Statement {-}

All materials and data, including the dissertation itself, are 
made available to the best of my ability. All articles in association with the
dissertation are/will be Open Access.

Protocols available: <https://protocols.io/workspaces/byoc>  
Code available: <https://github.com/bbartholdy>  
Data available: TBD

::: {.content-visible when-format="pdf"}
\clearpage
\thispagestyle{empty}
\vspace*{3cm}
\hfill\textit{En bar røv at trutte i}
\par
\hfill\vspace*{4cm} Jan Bartholdy
\vspace*{\fill}

\mainmatter
:::
