# Supplementary information {.unnumbered}

This dissertation contains a lot of supplementary materials. Therefore,
none of it is included in the dissertation itself. I will instead provide
links to the online material, which will be useful unless you are
reading a physical copy. If you are reading the physical book, well done---it means I like you enough,
or felt obligated enough, to provide you with a rare, albeit valueless, copy.
What's much less
likely is that you have borrowed a copy of this VERY
niche PhD dissertation from the library. First of all, why?
You have to options: you could tediously type out the entire url,
or you could just go read the online version. But
also, just go to the online version.

Most of the materials can be found on the Open Science Framework [(DOI: 10.17605/OSF.IO/3YX8M)](https://doi.org/10.17605/OSF.IO/3YX8M).

The oral biofilm model protocols are published on protocols.io [(DOI: 10.17504/protocols.io.dm6gpj9rdgzp/v1)](https://dx.doi.org/10.17504/protocols.io.dm6gpj9rdgzp/v1).

Article 1: 

- **DOI:** {{< var article1.doi >}}
- **Supplementary material:** {{< var article1.supp-mat >}}
- **Code:** {{< var article1.code >}}
- **Data:** {{< var article1.data >}}

Article 2:

- **DOI:** {{< var article2.doi >}}
- **Supplementary material:** {{< var article2.supp-mat >}}
- **Code and data:** {{< var article2.code >}}

Article 3: 

- **DOI:** {{< var article3.doi >}}
- **Supplementary material:** {{< var article3.supp-mat >}}
- **Code:** {{< var article3.code >}}
- **Data:** {{< var article3.data >}}
- **PCI_Archaeology recommendation:** {{< var article3.pci >}}
