{
  "hash": "cacac4cd93aeb4cb8da56b267bcd6137",
  "result": {
    "engine": "knitr",
    "markdown": "---\nengine: knitr\ntitle: Article 2\nsubtitle: Investigating Biases Associated with Dietary Starch Incorporation and Retention with an Oral Biofilm Model\nauthor: \n  - name: Bjørn Peare Bartholdy\n    orcid: 0000-0003-3985-1016\n    affiliations:\n      - ref: leiden\n  - name: Amanda G. Henry\n    orcid: 0000-0002-2923-4199\n    affiliations:\n      - ref: leiden\naffiliations:\n  - id: leiden\n    name: Leiden University\n    department: Faculty of Archaeology\n    city: Leiden\n    country: The Netherlands\n#shift-heading-level-by: 1\n---\n\n\n\n::: {.content-visible when-format=\"pdf\"}\n\n\\footnotesize\n\n**Co-authors and contributions:**\n\n- Amanda G. Henry, Leiden University\n\n<!-- generated with tenzing (https://rollercoaster.shinyapps.io/tenzing/) -->\nConceptualization: B.P.B. and A.G.H. Data curation: B.P.B. Formal analysis: B.P.B. Funding acquisition: A.G.H. Investigation: B.P.B. Methodology: B.P.B. and A.G.H. Resources: A.G.H. Software: B.P.B. Supervision: A.G.H. Visualization: B.P.B. Writing - original draft: B.P.B. Writing - review & editing: B.P.B. and A.G.H.\n\n**Cite as:**\n\nBartholdy, B. P., & Henry, A. G. (2022). Investigating Biases Associated With Dietary Starch Incorporation and Retention With an Oral Biofilm Model. Frontiers in Earth Science, 10. https://doi.org/10.3389/feart.2022.886512\n\n\\normalsize\n\n\n\n{{< pagebreak >}}\n\n\n\n\n\n:::\n\n::: {.content-visible when-format=\"html\"}\n\n\n{{< var article2.badges.status >}} {{< var article2.badges.version >}} {{< var article2.badges.doi >}} {{< var article2.badges.github >}}\n\n\n\n\n\n::: {.callout-note icon=\"false\"}\n\n# Summary {-}\n\nWe used our oral biofilm model, as described in Chapter 3, to look at how starch\ngranules are incorporated\ninto dental calculus. We 'fed' the biofilm with a known quantity of starch granules\nduring the growth period. Preliminary results suggest that a very small proportion\nof consumed starch is retained by the calculus. The size of starch granules also\ninfluences the likelihood of retention, with larger granules less likely to be\ntrapped in the calculus.\n\n:::\n:::\n\n\n\n\n\n\n\n## Introduction {#byocstarch-intro}\n\n<!-- basic introduction to the field, comprehensible to a scientist in any discipline -->\n<!-- Dental calculus is mineralised plaque. And it is pretty cool. -->\nDental calculus has proven to contain a wealth of \ndietary information in the form of plant microfossils \n[@henryCalculusSyria2008; @hardyStarchGranules2009], \nproteins [@hendyProteomicCalculus2018; @warinnerEvidenceMilk2014],\nand other organic residues [@buckleyDentalCalculus2014]. \nThis dietary information can be preserved within the mineralised dental plaque \nover many millennia, providing a unique window into the food-related behaviours of \npast populations \n[@henryCalculusSyria2008; @jovanovicNeolithicCalculus2021; @taoWheatCalculus2020] \nand extinct species [@henryNeanderthalCalculus2014; @hardyNeanderthalMedics2012]. \n\n<!-- more detailed background, comprehensible to scientists in related disciplines -->\nUntil recently, only a few studies directly investigated the presence of plant\nmicroremains\nin the dental calculus of archaeological remains. The ability to extract phytoliths\nfrom the dental calculus of archaeological fauna to investigate diet was first \nnoted by Armitage [-@armitageExtractionIdentification1975], \nand later by Middleton and Rovner [-@middletonOpalPhytoliths1994],\nand Fox and colleagues [-@foxPhytolithCalculus1996]. Starches and phytoliths were\nextracted from human dental calculus by Cummings and Magennis [-@cummingsMayanCalculus1997].  \nIn more recent years, the study of dental calculus has increased exponentially, \nand the wealth of information contained within the mineralised matrix has largely\nbeen acknowledged. The use of dental calculus spans a wide\nvariety of archaeological research areas, such as oral microbiome \ncharacterisation (including pathogens) through the analysis of DNA and proteins \n[@adlerSequencingAncient2013; @warinnerPathogensHost2014],\nmicrobotanical remains [@henryCalculusSyria2008; @hardyStarchGranules2009;\n@mickleburghNewInsights2012], \nother organic residues and proteins from dietary compounds \n[@buckleyDentalCalculus2014; @hendyProteomicCalculus2018], \nand nicotine use [@eerkensDentalCalculus2018]. Especially the extraction \nof starch granules has become a rich source of dietary\ninformation, as starch granules have proven to preserve well within dental calculus\nover a variety of geographical and temporal ranges \n[@pipernoStarchGrains2008; @henryNeanderthalCalculus2014; @taoWheatCalculus2020;\n@jovanovicNeolithicCalculus2021].\n\n<!-- clearly stating the general problem being addressed by this particular study -->\nDespite this, our knowledge of dental calculus and the incorporation pathways of \nthe various markers is limited [@radiniFoodPathways2017], as is our \nknowledge of information-loss caused by these pathways. Additionally, the methods\nwe use to extract and analyse dental calculus, and make inferences on past diets\nrepresent another potential source of bias. Studies on both archaeological and\nmodern individuals have explored these biases in more detail.\nExtraction methods were tested \nby Tromp and colleagues [-@trompEDTACalculus2017], specifically regarding\ndecalcification using HCl or EDTA. \nThe authors found significantly more starches with the EDTA extraction method \nthan the HCl extraction method; however, as noted by the authors, comparisons \ninvolving archaeological calculus are problematic due to variability between and \nwithin individuals. \nStudies conducted on modern humans [@leonardPlantMicroremains2015] \nand non-human primates [@powerChimpCalculus2015; @powerRepresentativenessDental2021] \nhave explored how well microremains (phytoliths and starches)\nextracted from dental calculus represent the actual dietary intake.\nThese studies are justifiably limited, \ndespite meticulous documentation and observation, due to unknown variables and \nuncertainty involved in this kind of *in vivo* research. Dental calculus is a complex \noral biofilm with a multifactorial aetiology and variable formation rates both \nwithin and between individuals [@jepsenCalculusRemoval2011; @haffajeeBiofilmPosition2009], \ncontributing to\nthe stochasticity of starch representation being observed in numerous studies.\nAdditionally, the concentration of oral $\\alpha$-amylase differs both between and\nwithin individuals [@froehlichEffectOral1987; @naterHumanAmylase2005],\ncausing different rates of hydrolysis of the starch granules present in the oral\ncavity. Add to this the effects of the many different methods\nof starch processing [@hardyRecoveringInformation2018], as well as post-depositional\nprocesses that are still being explored\n[@graneroStarchTaphonomy2020; @mercaderExaggeratedExpectations2018],\nand it becomes clear that using \ndental calculus to reconstruct diet is a highly unpredictable process.\n\nIn this exploratory study, we use an oral biofilm model to investigate the \nretention of starch granules within dental calculus in a controlled laboratory \nsetting, allowing us full control over dietary input. Our main questions concern\nthe representation of granules extracted\nfrom the calculus compared to the actual intake. How much of the original diet is \nincorporated into the calculus, and how much is recovered? \nIs there differential loss of information from specific dietary markers that affects \nthe obtained dietary information, and how does this affect the representation of \ndiet from extracted microremains?  \nWe find that, despite the absence of $\\alpha$-amylase in\nthe model, a limited proportion of the starch input is actually \nretained in the calculus. We also observed a shift in the size ratios of individual \nstarch granules that are incorporated into the calculus, and that the number of \nincorporated starch granules increases as the size of the calculus deposit \nincreases.\n\n\n\n## Materials and Methods\n\n### Biofilm formation\n\nIn this study we employ a multispecies oral biofilm model following a modified\nprotocol from Sissons and colleagues [-@sissonsMultistationPlaque1991] and\nShellis [-@shellisSyntheticSaliva1978]. In brief, a biofilm inoculated\nwith whole saliva was grown on a substrate suspended in artificial saliva, and\nfed with sugar (sucrose). After several days of growth, the biofilm was exposed\nto starch solutions. Mineralisation of the biofilm was aided by exposure to a\ncalcium phosphate solution. After 25 days of growth, the mineralised biofilm was\ncollected for further analysis. The setup comprises a polypropylene \n24 deepwell PCR plate (KingFisher 97003510) with a lid containing 24 pegs, which \nis autoclaved at 120&deg;C, 1 bar overpressure, for 20 mins. The individual pegs \nwere the substrata on which the calculus grew. Using this system allowed for easy\ntransfer of the growing biofilm between saliva, feeding solutions, \nand mineral solutions.\n\nThe artificial saliva (AS) is a modified version of the basal medium mucin (BMM)\ndescribed by Sissons and colleagues [-@sissonsMultistationPlaque1991]. \nIt contains 2.5 g/l partially purified mucin from porcine stomach (Type III, Sigma M1778), \n5 g/l trypticase peptone (Roth 2363.1), 10 g/l proteose peptone (Oxoid LP0085),\n5 g/l yeast extract (BD 211921), 2.5 g/l KCl, 0.35 g/l NaCl, 1.8 mmol/l CaCl~2~, \n5.2 mmol/l Na~2~HPO~4~ [@sissonsMultistationPlaque1991], 6.4 mmol/l NaHCO~3~ \n[@shellisSyntheticSaliva1978], 2.5 mg/l haemin. This is subsequently \nadjusted to pH 7 with NaOH pellets and stirring, autoclaved (15 min, 120&deg;C, \n1 bar overpressure), and supplemented with 5.8 $\\mu$mol/l menadione, 5 mmol/l urea, \nand 1 mmol/l arginine [@sissonsMultistationPlaque1991].\n\nFresh whole saliva (WS) for inoculation was provided by a 31-year-old<!--needless to say I am much older now...--> male donor \nwith no history of caries, who abstained from oral hygiene for 24 hours. No \nfood was consumed two hours prior to donation and no antibiotics were taken up \nto six months prior to donation. \nThe saliva was filtered through a sterilised (with sodium hypochlorite, 10--15% active chlorine) \nnylon cloth to remove particulates.\nSubstrata were inoculated with 1 ml/well of a two-fold dilution of WS in sterilised \n20% (v/v) glycerine for four hours at 36&deg;C, to allow attachment of the\nsalivary pellicle and plaque-forming bacteria. After initial inoculation, the \nsubstrata were transferred to a new plate containing 1 ml/well AS and incubated \nin a shaking incubator (Infors HT Ecotron) at 36&deg;C, 30 rpm. \nThe inoculation process was repeated on days 3 and 5. \nAS was partially refreshed once per day and fully refreshed every three days, \nthroughout the experiment, by transferring the substrata to a new plate containing \nstock AS. To feed the bacteria, the substrata were transferred to a new plate, containing \n5% (w/v) sucrose, for six minutes twice daily, except on inoculation days \n(days 0, 3, and 5), where the samples only received one sucrose treatment after\ninoculation. \n\nStarch treatments were initiated on day 9 to avoid starch granule counts being \naffected by $\\alpha$-amylase hydrolysis from saliva inoculation days. \nAn $\\alpha$-amylase (EC 3.2.1.1) activity\nassay was conducted to confirm that no amylase was present in the model before\nstarch treatments started. Starch treatments replaced sucrose treatments, occurring twice per day\nfor six minutes. The starch treatments involved transferring the substrata to a \nnew plate containing a 0.25% (w/v) starch from potato (Roth 9441.1) solution, a 0.25% (w/v) starch from wheat (Sigma S5127) solution, and a 0.5% (w/v) mixture of equal\nconcentrations (w/v) wheat and potato. All starch treatments were created in dH~2~O\nwith 5% (w/v) sucrose. Before transferring biofilm samples to the starch treatment\nplate, the plates were agitated to keep the starches in suspension in the\nsolutions. During treatments, the rpm was increased to 60 to facilitate contact\nbetween starch granules and biofilms.\n\nAfter 15 days, mineralisation was encouraged with a \ncalcium phosphate monofluorophosphate urea (CPMU) solution containing \n20 mmol/l CaCl~2~, 12 mmol/l NaH~2~PO~4~, 5 mmol/l Na~2~PO~3~F, 500 mmol/l urea, \nand (0.04 g/l MgCl)\n[@pearceConcomitantDeposition1987; @sissonsMultistationPlaque1991].\nThe substrata were submerged in 1 ml/well CPMU for six minutes, five times \ndaily, in a two-hour cycle. During the mineralisation period, starch treatments\nwere reduced to once per day after the five CPMU treatments. This process was repeated \nfor 10 days until the end of the experiment on day 24 \n(see @fig-protocol for an overview of the protocol).\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Overview of experiment protocol including the plate setup.](figures/protocol_overview.png){#fig-protocol fig-align='center' fig-pos='H' width=4.27in}\n:::\n:::\n\n\nAll laboratory work was conducted in sterile conditions under a laminar flow hood \nto prevent starch and bacterial contamination. Control samples that only received\nsucrose as a treatment were included to detect starch contamination from the\nenvironment or cross-contamination from other wells in the same plate.\n\n### Amylase activity detection\n\nAn $\\alpha$-amylase (EC 3.2.1.1) activity assay was conducted on artificial\nsaliva samples collected from the plate wells on days 3, 6, 8, 9, 10, 12, and 14. \nWhole saliva samples were collected on days 0, 3, and 5 as positive controls.\nCollected samples were stored at 4&deg;C until the assay was conducted on day 18. \nAll samples and standard curves were run in triplicates on two separate plates.\nPositive control saliva samples were compared against a standard curve containing \nH~2~O, while artificial saliva samples were compared against a standard curve\ncontaining stock AS (due to the colour of artificial saliva).\nTwo photometric readings were conducted for each plate with a 540 nm filter on a \nMultiskan FC Microplate Photometer (Thermo Scientific 51119000). \nThe protocol is a modified version of an Enzymatic Assay of $\\alpha$-Amylase\n(<https://www.sigmaaldrich.com/NL/en/technical-documents/protocol/protein-biology/enzyme-activity-assays/enzymatic-assay-of-a-amylase>) [@bernfeldAmylase1955], which measures the amount of\nmaltose released from starch by $\\alpha$-amylase activity. Results are reported\nin units (U) per mL enzyme, where 1 U releases 1 $\\mu$mole of maltose in 6 minutes.\nThe detailed protocol can be found here: <https://www.protocols.io/view/amylase-activity-bw8jphun>.\n\n### Treatment solutions\n\nA 1 ml aliquot of each starch solution was taken, from which 10 $\\mu$l was mounted \non a microscope slide with an 18 x 18 mm coverslip, and counted under a light microscope\n(Zeiss Axioscope A1). For wheat and mixed treatment samples, we counted three \nslide transects (at ca. 1/4, 1/2, and 3/4 of the slide), and the sample counts \nwere extrapolated to the total number of granules exposed to the samples over 16\ndays of treatments (see Supplementary Material for more details). For potato\ntreatment samples, the whole slide was counted.\n\n### Extraction method\n\nExtraction of starches from the calculus samples was performed by dissolving the\ncalculus in 0.5 $\\tiny{M}$ ethylenediaminetetraacetic acid (EDTA) \n[@trompEDTACalculus2017; @lemoyneCalculusPretreatments2021; @modiCalculusMethodologies2020], \nand vortexing for 3 days until the sample was completely dissolved. \nTwenty $\\mu$l of sample was mounted onto a slide with an 18x18 mm coverslip.\nWhen transferring the sample to the slide, the sample was homogenised using \nthe pipette to ensure that the counted transects were representative of the \nwhole slide. The count from the slide was extrapolated to the whole sample\n(see Supplementary Material for more detail).\n\nBoth wheat and potato granules were divided into three size categories: \nsmall (<10 $\\mu$m), medium (10 -- 20 $\\mu$m), and large (>20 $\\mu$m). \n\n### Statistical analysis\n\nStatistical analysis was conducted in R version 4.3.3 (2024-02-29)  [@Rbase] and\nthe following packages: tidyverse [@tidyverse2019], broom [@Rbroom], \nhere [@Rhere], and patchwork [@Rpatchwork].\n<!-- R packages used -->\n\nTo see if biofilm growth was differently affected by starch treatments, a \none-way ANOVA with sample weight as the dependent variable (DV) and treatment \nas the grouping variable (GV) was conducted.\nTo analyse granule counts and calculate size proportions, mean counts for each \ntreatment were taken across\nboth experimental plates, resulting in a mean count for each\ngranule size category within each treatment.\n\nPearson's *r* was conducted on sample weight and total starch count, as well as sample\nweight and starch count per mg calculus. The total count for each sample within a\ntreatment was standardised by z-score to account for the differences in magnitude\nbetween the potato and wheat counts.\nThis was applied to total biofilm weight and starch count per mg \ncalculus (also z-score standardised) to account for differences in starch \nconcentration in the calculus [as per \n@wesolowskiEvaluatingMicrofossil2010].\n\n\n\n## Results\n\nAll samples yielded sufficient biofilm growth and starch incorporation to be \nincluded in the analysis (@fig-microscope), resulting in a total of 48 biofilm\nsamples (two plates of 24), 45 of which were used for analysis (three samples\nwere set aside for later analysis). Most control samples contained no starch\ngranules, while some contained negligible quantities (see Supplementary Material).\n\n::: {#fig-microscope layout-ncol=2}\n\n![](figures/starches_w_bar.jpg)\n\n\n![](figures/st2C3.2-mix.jpg)\n\n![](figures/st1B4-wheat.jpg)\n\n![](figures/2D2-potato.jpg)\n\nMicroscope images of biofilm samples that were exposed to the starch solutions.\nStarch granules can be seen within bacterial communities and isolated. Scale bar = 20 μm.\n\n:::\n\n### No amylase activity detected in the model\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\nNo $\\alpha$-amylase activity was detected in any of the artificial\nsaliva samples from any of the days that were sampled. Only positive controls\n(saliva)\ncontained amylase activity that could be detected in the assay, ranging from\n9.93 to 30.2 U/mL enzyme \n(full results can be found in the Supplementary Material).\nThe results are not comparable to other studies presenting $\\alpha$-amylase activity\nlevels in humans, as the unit definition may differ; \nhowever, they are sufficient to show that there is no activity in the model.\n\n### Treatment type had minimal effect on biofilm growth\n\nA one-way ANOVA suggests that the type of starch used during the biofilm \ngrowth period had a minimal effect on the growth of the biofilm \n(expressed as total dry weight of the sample), F(3, 43)\n= 1.16, p = 0.335.\nA summary of sample weights is available in @tbl-anova.\n\n\n::: {#tbl-anova .cell layout-align=\"center\" tbl-cap='Summary statistics for biofilm dry-weights (in mg) by treatment.'}\n::: {.cell-output-display}\n\n\n|Treatment | Mean|   SD|  Min|   Max|\n|:---------|----:|----:|----:|-----:|\n|control   | 5.44| 2.45| 1.67| 11.20|\n|mix       | 4.28| 1.95| 1.50|  8.44|\n|potato    | 6.25| 2.07| 2.54|  8.92|\n|wheat     | 5.53| 3.45| 0.56|  9.80|\n\n\n:::\n:::\n\n\n### Starch counts\n\n<!-- starch counts in the solutions -->\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n<!-- starch counts in the samples -->\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\nIt was not possible to differentiate between potato and \nwheat starches smaller than ca. 10 $\\mu$m. These were counted as wheat,\nas we assumed that the majority of the small granules were wheat. We make this \nassumption based on the counts of small starches in the wheat-only and potato-only\nsolutions. Of the combined amount of small starches in these two solutions, \n99.2%\nare from wheat.\n<!-- count of small granules from wheat solution divided by the sum of small granules \nfrom the potato and wheat solutions -->\n\n<!-- absolute solution counts compared to absolute sample counts. does exposure\nto higher quantities of starches mean more incorporated starches? -->\nThe separate wheat and potato solutions were made with a 0.25% (w/v) starch\nconcentration, while the mixed-starch solution was made with 0.25% (w/v) of each\nstarch, with a total concentration of 0.50% (w/v).\nThe mixed treatment had the highest absolute count of starch granules in solution (mean = \\ensuremath{2.9\\times 10^{7}}),\nwhile the biofilms exposed to the wheat solution preserved the greatest number of\ngranules \n(mean = \\ensuremath{2.77\\times 10^{4}}). \nThe potato treatment had the lowest absolute counts in both the solution \n(\\ensuremath{3.02\\times 10^{6}})\nand in the biofilm samples \n(4850) \n(@tbl-solution-count and @tbl-sample-count).\n\n\n::: {#tbl-solution-count .cell layout-align=\"center\" tbl-cap='Mean starch counts from solutions, including the proportional makeup of the different sizes of granules.'}\n::: {.cell-output-display}\n\n\n|Solution |Starch |Small (%)        |Medium (%)      |Large (%)       |Total (%)         |\n|:--------|:------|:----------------|:---------------|:---------------|:-----------------|\n|mix      |potato |                 |1051733 (53.1%) |928000 (46.9%)  |1979733 (100.0%)  |\n|mix      |wheat  |18838400 (69.7%) |6403200 (23.7%) |1794133 (6.6%)  |27035733 (100.0%) |\n|mix      |both   |18838400 (64.9%) |7454933 (25.7%) |2722133 (9.4%)  |29015467 (100.0%) |\n|potato   |potato |123733 (4.1%)    |1337867 (44.4%) |1554400 (51.5%) |3016000 (100.0%)  |\n|wheat    |wheat  |16139467 (63.5%) |6434133 (25.3%) |2830400 (11.1%) |25404000 (100.0%) |\n\n\n:::\n:::\n\n::: {#tbl-sample-count .cell layout-align=\"center\" tbl-cap='Mean starch counts extracted from samples with standard deviation (SD), including the proportion of granule sizes of the total count.'}\n::: {.cell-output-display}\n\n\n|Treatment |Starch |Small (%)      |    SD|Medium (%)    |    SD|Large (%)    |   SD|Total (%)    |    SD|\n|:---------|:------|:--------------|-----:|:-------------|-----:|:------------|----:|:------------|-----:|\n|mix       |potato |               |      |1959 (79.6%)  |  1801|501 (20.40%) |  446|2460 (100%)  |  2189|\n|mix       |wheat  |9515 (54.60%)  |  8860|6522 (37.4%)  |  6026|1381 (7.93%) | 1196|17417 (100%) | 15878|\n|mix       |both   |9515 (47.90%)  |  8860|8480 (42.7%)  |  7653|1882 (9.47%) | 1596|19877 (100%) | 17768|\n|potato    |potato |351 (7.24%)    |   297|3565 (73.6%)  |  2402|930 (19.20%) |  929|4846 (100%)  |  3316|\n|wheat     |wheat  |15235 (55.00%) | 11944|12148 (43.9%) | 11052|1953 (7.06%) | 2016|27680 (100%) | 23554|\n\n\n:::\n:::\n\n\n#### Proportion of available starches incorporated in samples\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\nThe proportion of total starches from the solutions that were incorporated \ninto the samples ranged from \n0.06% to 0.16%,\nwith potato granules being more readily incorporated than wheat in both the\nseparated- and mixed-treatment samples (@tbl-sample-prop). \nThere is an inverse relationship between the absolute starch count in the solutions \nand the proportional incorporation of starches in the biofilm samples, i.e., potato \nhad the lowest absolute count in solutions, but the highest proportional \nincorporation, and vice versa for the mixed treatment.\n\n\n::: {#tbl-sample-prop .cell layout-align=\"center\" tbl-cap='The mean percentage of starches from the solutions that were incorporated into the samples.'}\n::: {.cell-output-display}\n\n\n|Treatment |Starch |Small |Medium |Large |Total |\n|:---------|:------|:-----|:------|:-----|:-----|\n|mix       |potato |      |0.19%  |0.05% |0.12% |\n|mix       |wheat  |0.05% |0.10%  |0.08% |0.06% |\n|mix       |both   |0.05% |0.11%  |0.07% |0.07% |\n|potato    |potato |0.28% |0.27%  |0.06% |0.16% |\n|wheat     |wheat  |0.09% |0.19%  |0.07% |0.12% |\n\n\n:::\n:::\n\n\n<!-- mixed treatments -->\nWheat incorporation was most affected in the mixed-treatment samples, with only\n0.06% of the total available starches being incorporated into\nthe sample, compared to\n0.16%\nin the separated wheat treatment.\n\n#### Size ratios differ between solutions and samples\n\n<!-- size proportions -->\n<!-- pie charts -->\n\n<!-- overall size trends -->\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n\nOverall, medium starch granules had a higher mean rate of incorporation \n(0.171%) \nthan small \n(0.120%) \nand large \n(0.066%) \nstarch granules across all treatments, while large potato starches had the lowest \nrate of incorporation across all treatments.\n\n<!-- separated and mixed treatments -->\nThe difference in incorporation between the size categories resulted in a change\nin size ratios between the original starch solutions and the extracted samples.\nLarge potato granules (> 20 $\\mu$m) were most affected, with a \n32.3% \ndecrease in relative abundance in the potato-only treatment, and a\n26.5% \ndecrease in mixed treatments. Medium granules increased in relative abundance \nacross all samples, while small granules decreased in wheat treatments and \nincreased in potato treatments \n(@fig-ratio-plots).\n\n<!-- Proportion and size ratios are the most important points to be made -->\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Proportion of sizes of starch granules from solutions (outer ring) and treatment samples (inner ring) in separated wheat (A) and potato (B) treatments, and mixed wheat (C) and potato (D) treatments.](figures/byoc-starch-fig-ratio-plots-1.pdf){#fig-ratio-plots fig-align='center' fig-pos='H'}\n:::\n:::\n\n\n#### Biofilm weight correlated positively with extracted starch counts\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\nPearson's *r* suggests a \nstrong positive \ncorrelation between the total weight of the biofilms and the total starch count \n(standardised by z-score) extracted from the samples across treatments, \n*r* = 0.659, \n90%CI[0.463, 0.794],\np < 0.001\n([@fig-cor-plot]A).\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Scatter plots of (A) sample weight in mg and standardised starch count by z-score for separated treatments, and (B) sample weight in mg and standardised count of starch grains per mg calculus.](figures/byoc-starch-fig-cor-plot-1.pdf){#fig-cor-plot fig-align='center' fig-pos='H'}\n:::\n:::\n\n\nThe same test was applied to total biofilm weight and starch count per mg \ncalculus (also standardised by z-score), resulting in a weak positive correlation, \n*r* = 0.3, \n90%CI[0.0618, 0.506],\np = 0.0403\n([@fig-cor-plot]B).\n\n\n\n## Discussion\n\n<!-- Big summary/important statement for the science -->\nHere, we have provided a method for exploring the incorporation of dietary \nstarches into the mineral matrix of a dental calculus biofilm model. Our results show\nthat a very low proportion of the starches exposed to the biofilm during growth are\nretained in the mineral matrix, and that the size of the starch granules\nmay affect the likelihood of incorporation. The proportions of starch granules \n(of all sizes) present in the extracted samples were similar across all treatments\n(0.06% to 0.16%), \ndespite large differences in absolute granule counts between wheat \n(mean = 25,404,000) \nand potato\n(mean = 3,016,000)\nsolutions.  \nThe absolute counts, however, differed more visibly between treatments and was\nproportional with the total count of granules in the treatment solutions. Wheat \nand mixed solutions had the highest absolute mean count of starch granules, and \nalso had the highest absolute mean count of starch granules extracted from the \ndental calculus (@tbl-solution-count and @tbl-sample-count).\nThis suggests that the starches that are more frequently consumed will be present\nin higher quantities in the dental calculus, at least prior to inhumation and \ndegradation in the burial environment. \nDespite the low proportion of granules recovered from the model calculus \n(0.06% to 0.16%),\nthe absolute counts were still substantially greater than counts recovered from \narchaeological remains \n[@trompDietaryNondietary2015; @trompEDTACalculus2017; @wesolowskiEvaluatingMicrofossil2010], which could in part be due to the \nlack of oral amylase activity in our model. \n<!-- Scientific findings as extension of previous work -->\nPrevious research conducted on dental calculus from contemporary humans and non-human\nprimates suggest a high level of stochasticity involved in the retention of \nstarch granules in dental calculus, and that starch granules extracted from dental \ncalculus are underrepresented with regard\nto actual starch intake, which is consistent with our findings (illustrated by high\nstandard deviations and low proportional incorporation).\nLeonard and colleagues [-@leonardPlantMicroremains2015] found individual\ncalculus samples to be a poor predictor of diet in a population, as many of the \nconsumed plants were missing from some individual samples, but were present in others.   \nPower and colleagues [-@powerChimpCalculus2015] \npresented similar findings in non-human primates, where phytoliths were more\nrepresentative of individual diets than starch granules.\nThe size bias is also consistent with the findings by Power and colleagues\n[-@powerChimpCalculus2015],\nwho found that plants producing starches 10--20 $\\mu$m in\nsize were over-represented; however, the representation of granules larger than\n20 $\\mu$m in their study is unclear.\n\nWe have also shown that the size of the starch granules influences the likelihood\nof incorporation into the calculus. Starch granules larger than 20 $\\mu$m in\nmaximum length were underrepresented in the calculus samples compared to the original \nstarch solutions, an effect that was consistent across all three treatments. Medium\ngranules (10--20 $\\mu$m) were often over-represented\n(@tbl-sample-prop, and @fig-ratio-plots).\nLarge potato granules were most affected, potentially because of the greater\nsize-range. They can reach up to 100 $\\mu$m in maximum length, whereas wheat \ngranules generally only reach up to 35 $\\mu$m \n[@gismondiStarchGranules2019; @haslamDecompositionStarch2004; @seidemannStarchAtlas1966, 174-176].\nGranule morphology may also play a role. Large wheat granules \nare lenticular and have a larger surface area compared \nto volume, whereas large potato granules are ovoid and have a larger volume\ncompared to surface area \n[@vandeveldeStarchMorphology2002; @janeAnthologyStarch1994; @reichertStarchBible1913b, 364-365; @seidemannStarchAtlas1966, 174-176]. \nAnother potentially important factor \nfrom our results is the size of the calculus deposit. We found a \nstrong positive correlation between size of biofilm deposit and\nretained starch granules ([@fig-cor-plot]A), meaning larger calculus deposits\ncontain a higher quantity of granules; a result that contradicts findings from\narchaeological contexts\n[@wesolowskiEvaluatingMicrofossil2010; @dudgeonDietGeography2014].\nWhen the concentration of starch granules per mg calculus is considered, the\ncorrelation is weaker, but still present ([@fig-cor-plot]B).\nWhile the larger deposits contain a higher absolute count, our findings also suggest\nthat they contain a slightly higher concentration of starches. This may also explain\nthe lower mean retention of starch granules in mixed treatments compared to\nwheat treatments. Wheat treatment samples (mean = 5.53 mg) were on average larger than mixed treatment samples (mean = 4.28 mg) (@tbl-anova); and while mixed treatment solutions contained the highest mean overall\ngranule counts, wheat treatment samples had the highest mean starch retention.\nFurther research is needed to determine why this differs from previous archaeological\nfindings.\n\n<!-- How are starch granules trapped in dental calculus? Does anyone actually know? \n-->\nThe mechanism by which starch granules are incorporated into plaque and calculus \nremains largely unknown, and few studies have directly investigated potential\nmechanisms. We know that a proportion of the starch granules entering \nthe mouth can become trapped in the plaque/calculus, and can be recovered from\narchaeological samples of considerable age \n[@henryNeanderthalCalculus2014; @buckleyDentalCalculus2014; @wuDietEarliest2021]. \nStudies have also shown that not all starch granules come from a dietary source. \nOther pathways include cross-contamination from plant interactions in soil, such \nas palm phytoliths adhering to the skin of sweet potatoes \n[@trompDietaryNondietary2015], \nor accidental ingestion not related to food consumption \n[@radiniFoodPathways2017; @radiniMedievalWomen2019].  \nWhen starch granules enter the mouth, whether through ingestion of food or accidental\nintake, they immediately encounter multiple obstacles. It is likely\nthat the bulk of starch granules are swallowed along with the food, and are \nonly briefly present in the oral cavity. Other granules that are broken off\nduring mastication may be retained in the dentition through attachment to \ntooth surfaces (including plaque and dental calculus) and mucous membranes \n[@kashketFoodRetention1991; @doddsCarbohydrateRetention1988].\nBacteria also have the ability to adhere to starch granules \n[@toppingResistantStarch2003],\nwhich would allow starches to attach to bacterial communities within the biofilm.\nThese granules are then\nsusceptible to mechanical removal by the tongue, salivary clearance, and hydrolysis\nby $\\alpha$-amylase [@kashketFoodParticles1996].\nThe susceptibility of granules to hydrolysis depends on the crystallinity and size\nof the starch granule, as well as the mode of processing. Smaller and pre-processed\n(e.g., cooked) starch granules are more susceptible to enzymatic degradation, \nwhile dehydrated starches will have a reduced susceptibility\n[@lingstromStarchyFood1994; @francoStarchDegradation1992; @haslamDecompositionStarch2004; \n@bjorckStarchProcessing1984; @henryCookingStarch2009].\nCracks on the surface of the dental calculus, as well as unmineralised islands \nand channels may also be able to contain starch granules \n[@powerSEMCalculus2014; @tanCalculusUltrastructure2004; @charlierSEMCalculus2010].\nStarch granules that are trapped in these pockets are (at least to some extent) \nprotected from aforementioned clearance mechanisms, especially once\na new layer of plaque has covered the surface of the plaque/calculus. \nThe size bias against large granules (>20 $\\mu$m) from both wheat and potato \n(@tbl-sample-prop) may give further credence to\nthis incorporation pathway, as the smaller starch granules have an advantage over\nlarger granules, and can be stored in larger quantities.\nThis was also suggested by Power and colleagues [-@powerSEMCalculus2014], who\nobserved clusters of starches within dental calculus, rather than an even \ndistribution across the surface of the dental calculus.\nGranules trapped \nin plaque/calculus may still be susceptible to hydrolysis, as $\\alpha$-amylase has\nthe ability to bind to both tooth enamel and bacteria within a biofilm and retain\na portion of its hydrolytic activity\n[@scannapiecoSalivaryAmylase1993; @nikitkovaStarchBiofilms2013; @tanBacterialViability2004; @tanCalculusUltrastructure2004].\nAfter the death of an individual, starches within dental calculus are susceptible \nto further degradation by post-depositional processes, depending on burial environment \n(pH, temperature, moisture content, microorganisms)\n[@henryCookingStarch2009; @graneroStarchTaphonomy2020; @haslamDecompositionStarch2004; @francoStarchDegradation1992].\nFuture study should explore how burial affects the recovery of starch from the\nbiofilm model. <!-- I may get to it eventually, but it would be great if someone else could look at this! -->\n\n<!-- in summary: we know very little about the mechanism behind how starches \nbecome trapped in dental calculus, but it would be nice to find out more. -->\n\n<!-- limitations of the platform show which questions would be unanswered -->\nThe absence of $\\alpha$-amylase in the model is a limitation of this study, as \nthe total granule counts were not subject to hydrolysis. This would likely have \nreduced and affected the size ratios, as smaller starches may be more \nsusceptible to hydrolysis \n[@francoStarchDegradation1992; @haslamDecompositionStarch2004]. The absence may\nalso affect biofilm growth due to the lack of amylase-bacterium interactions\n[@nikitkovaStarchBiofilms2013]. Conversely, the model may benefit from the\nabsence of $\\alpha$-amylase, because it can allow us to directly explore\nits effect on starch counts in future experiments, where $\\alpha$-amylase can be \nadded to the model in concentrations similar to those found in the oral cavity\n[@scannapiecoSalivaryAmylase1993]. \nWe are able to show how absolute counts in the treatments cause a difference in\nincorporation. However, this\nwas merely a side-effect of the difference in the number of granules in potato and \nwheat solutions of the same concentration (w/v). Further research should test \nmultiple differing concentrations of the same starch type.\nThe use of EDTA may also have affected counts. While previous studies have shown \nnegligible morphological changes caused by exposure to EDTA \n[@trompEDTACalculus2017; @lemoyneCalculusPretreatments2021; @modiCalculusMethodologies2020], \nthese studies have not considered changes to separate size\ncategories within starch types, and whether shifts in size ratios occur due to\nexposure to the pre-treatment chemicals.\nThe total number of granules on a slide often exceeded a number that \nwas feasible to count in a reasonable time period, so we calculated the total \ncounts by extrapolating from three slide transects. \nThus, we reasonably assume that the three transects are a good representation \nof the entire slide, and that the distribution of all granules on the slide is \nrelatively homogeneous.   \nFinally, we only used native starches in the experimental procedure and the results \nwill likely differ for processed starches [@graneroStarchTaphonomy2020]. \nBased on the comparatively low counts obtained by Leonard\nand colleagues [-@leonardPlantMicroremains2015, Supplement 2], processing and amylase\nmay have a substantial effect on starch granule retention in the oral cavity.\n\n<!-- How this engineering will facilitate future research -->\n\nWhile we are unable to sufficiently address the \nmechanism(s) of starch incorporation with the data obtained in this study, \nthe dental calculus model presented here is uniquely suited to explore \nthese questions and may improve interpretations of dietary practices in past \npopulations. Further analyses using this model can address the call for more \nbaseline testing of biases associated with dietary research conducted on dental calculus \n[@lemoyneCalculusPretreatments2021].\nOur high-throughput experimental setup allows us a\nhigher degree of control over the factors that influence starch incorporation and\nretention, such as dietary intake, differential survivability of starches, \nand inter- and intra-individual variation in plaque accumulation and mineralisation.\nThe latter is especially difficult to control *in vivo* as it is influenced by \nnumerous factors including genetics, diet, salivary flow, and tooth position and\nmorphology \n[@jepsenCalculusRemoval2011; @simonsoroOralGeography2013; @proctorSpatialGradient2018; @fagernasMicrobialBiogeography2021; @haffajeeBiofilmPosition2009], \nas well as evolutionary differences [@yatesOralMicrobiome2021]. The set of\nlimitations for our model differ from *in vivo* methods and, as such, we expect\nour model to complement the results and interpretations of existing and new\n*in vivo* studies.\nIt can also facilitate training of students and researchers on methods of \ndental calculus analysis, such as starch and phytolith extraction and \nidentification, where it can replace the use of finite archaeological resources.  \n\n<!-- we still need to replicate results and do more science... but pretty cool, right? -->\n\n\n\n## Conclusion\n\nThis preliminary study shows that a very small proportion of the input starch\ngranules are retained in a dental calculus model. This and previous studies \nhave shown that calculus has a low capacity for retention of starch granules, \nan effect that is compounded by diagenetic effects in archaeological remains, \nresulting in low overall counts of extracted granules. \nThe proportion of starches consumed will in many cases be reflected \nin the quantity\nof starches extracted from the dental calculus---i.e., the more starch granules\nentering the oral cavity, the more will be recovered from extraction---at \nleast in modern calculus samples unaffected by diagenesis and hydrolysis.\nWhether or not this also applies to archaeological samples remains to be tested.\nAdditionally, we have\nshown that the size of granules will influence the likelihood of incorporation, \nas large (>20 $\\mu$m) starches have a decreased incorporation rate, medium \n(10--20 $\\mu$m)\nstarches an increased rate, and small (<10 $\\mu$m) granules remained somewhat\nconstant. The size of calculus deposit also seems to influence the capacity of \ngranule incorporation; as the size of the deposit increases, so does the\nabsolute count of incorporated granules.  \nWhile we have shown multiple factors that influence the likelihood \nof incorporation, the process still appears to be somewhat stochastic. Further\nresearch is needed to make sense of the contributing factors, and to explore the\nmechanisms of intra-oral starch incorporation and retention in dental calculus.\nThe oral biofilm model described in this study provides a method\nto explore the incorporation and extraction of dietary compounds from dental calculus \nin a controlled laboratory setting. We do not expect our model to replace *in vivo*\nmethods; instead, it can provide a complementary means to address the limitations\nof *in vivo* studies, and unearth the potential biases associated \nwith dietary research conducted on archaeological dental calculus. \n\n\n\n## References cited {.unnumbered}\n",
    "supporting": [
      "04-article_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{},\"value\":[]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}