# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  workflow_dispatch:
  push:
    branches: 
      - main
    # paths-ignore:
    #   - '**.md'
    paths:
      - '**.qmd'
      - '**.yml'
      - '**.bib'
      - '**.scss'
      - '**.md'

name: build

jobs:
  build-book:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Include submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: r-lib/actions/setup-pandoc@v2
        #with:
          #pandoc-version: '3.1.12'
            
      - name: Install missing system dependencies
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install libglpk-dev libcurl4-openssl-dev libfontconfig1-dev libharfbuzz-dev libfribidi-dev libfreetype6-dev libpng-dev libtiff5-dev libjpeg-dev libgsl-dev

      - name: Install Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          tinytex: true
          #version: 1.3.450

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
          r-version: renv
          
      - uses: r-lib/actions/setup-renv@v2

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        if: ${{ success() }}
        with:
          target: netlify
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          
      # - name: Build Quarto site
      #   run: |
      #     quarto render --to all
      #   
      # - name: Deploy to Netlify
      #   env:
      #     NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      #     NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      #   run: |
      #     npm install netlify-cli -g
      #     netlify deploy --prod --dir _book
      #     

